ignore-patterns:
  - docs/*
  - packages/grid_control/backends/htcondor_wms/*
  - packages/grid_control_cms/DashboardAPI/*
  - packages/grid_control_cms/Lexicon.py
  - packages/grid_control_cms/share/fragmentForCMSSW.py
  - packages/grid_control_gui/xmpp/*
  - packages/python_compat_json.py
  - packages/python_compat_tarfile.py
  - packages/python_compat_urllib2.py
  - packages/requests/*
python-targets:
  - 2
  - 3
strictness: veryhigh
max-line-length: 160
pylint:
  disable:
    - C0103
    - broad-except
    - cell-var-from-loop
    - redefined-builtin
    - too-many-arguments
    - unused-argument
pep8:
  disable:
    - E251
    - E261
    - N802
    - N803
    - N806
    - W191
