language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
os:
  - linux
before_install:
  - pip install codecov
  - pip install 'coverage<4'
script:
  - export WRAPPER='coverage run -a'
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy'* ]]; then export WRAPPER=''; fi
  - $WRAPPER ./go.py -s -o '[jobs] continuous = False' docs/examples/ExampleS1_stresstest.conf
  - $WRAPPER ./go.py -G --debug docs/examples/ExampleS1_stresstest.conf
  - $WRAPPER ./go.py docs/examples/ExampleS1_stresstest.conf
  - diff ExampleS1_stresstest.list docs/examples/ExampleS1_stresstest.list.ref
  - $WRAPPER ./testsuite/cms/TEST_lumifilter.py
  - $WRAPPER ./testsuite/cms/TEST_lumiproc.py
  - $WRAPPER ./testsuite/config/TEST_configAPI1.py
  - $WRAPPER ./testsuite/config/TEST_configAPI2.py
  - $WRAPPER ./testsuite/config/TEST_configAPI3.py
  - $WRAPPER ./testsuite/config/TEST_configHandlers.py
  - $WRAPPER ./testsuite/config/TEST_config.py
  - $WRAPPER ./testsuite/config/TEST_configTyped.py
  - $WRAPPER ./testsuite/config/TEST_configView.py
  - $WRAPPER ./testsuite/config/TEST_matcher.py
  - $WRAPPER ./testsuite/datasets/TEST_dataresync1.py
  - $WRAPPER ./testsuite/datasets/TEST_dataresync2.py
  - $WRAPPER ./testsuite/datasets/TEST_dataresync3.py
  - $WRAPPER ./testsuite/datasets/TEST_dataresync4.py
  - $WRAPPER ./testsuite/datasets/TEST_dataresync_meta.py
  - $WRAPPER ./testsuite/datasets/TEST_dataresync_reorder.py
  - $WRAPPER ./testsuite/datasets/TEST_provider.py
  - $WRAPPER ./testsuite/datasets/TEST_splitter.py
  - $WRAPPER ./testsuite/parameters/TEST_config_param.py
  - $WRAPPER ./testsuite/parameters/TEST_padapter1.py
  - $WRAPPER ./testsuite/parameters/TEST_padapter.py
  - $WRAPPER ./testsuite/parameters/TEST_pfactory.py
  - $WRAPPER ./testsuite/parameters/TEST_psource.py
  - $WRAPPER ./testsuite/TEST_broker.py
  - $WRAPPER ./testsuite/TEST_jobselector.py
  - $WRAPPER ./testsuite/TEST_proxy.py
  - $WRAPPER ./testsuite/TEST_utils.py
  - $WRAPPER ./testsuite/TEST_webservice.py
after_success:
  - codecov
